name: Docker Image CI

on:
  push:
    branches: [ "test-docker" ]
  pull_request:
    branches: [ "test-docker" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ vars.ACR_HOST }}
        username: ${{ vars.ACR_USER }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ vars.ACR_HOST }}/${{ vars.BACKEND_IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}

